### ISSUE TITLE
Install error 

### ISSUE THREAD

**Issue by ahill818** [ncareol/homebrew-lrose-solo3#4] opened 2016-05-26 20:16 UTC
Terminal output with error. Is this a c++ compiler issue?

This is with MacOS 10.10.5

==> make install
Last 15 lines from /Users/severe/Library/Logs/Homebrew/solo3/02.make:
                             > >
/usr/local/Cellar/libsigc++/2.8.0/include/sigc++-2.0/sigc++/functors/slot.h:576:24: error: use of undeclared identifier 'blocked'
      if (!empty() && !blocked())
                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [ASpeckleCmd.o] Error 1
make[1]: *** Waiting for unfinished jobs....
20 errors generated.
20 errors generated.
make[1]: *** [AddValueCmd.o] Error 1
make[1]: *** [AddFieldCmd.o] Error 1
20 errors generated.
make[1]: *** [AbsoluteValueCmd.o] Error 1
make: *** [install-recursive] Error 1

**Comment by burghart** [comment] 2016-06-08 15:02
This appears to be a duplicate of issue #3

**Closed by burghart** 2016-06-08 15:02 UTC
Labels: duplicate
